## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os

def build(bld):

    # Find the kodo-c shared library in the local "lib" folder
    kodoc_path = os.path.join(bld.path.abspath(), 'lib')
    bld.read_shlib('kodoc', paths=[kodoc_path])

    def set_properties(obj):
        obj.includes = ['#', 'include']
        obj.cxxflags = ['-std=c++11']
        obj.use = obj.ns3_module_dependencies + ['kodoc']
        obj.rpath = [kodoc_path]
        obj.install_path = None

    obj = bld.create_ns3_program('kodo-recoder',
                                 ['core', 'applications', 'point-to-point',
                                  'point-to-point-layout', 'internet'])
    obj.source = 'kodo-recoder.cc'
    set_properties(obj)

    obj = bld.create_ns3_program('kodo-wifi-broadcast',
                                 ['core', 'applications', 'point-to-point',
                                  'point-to-point-layout', 'internet', 'wifi'])
    obj.source = 'kodo-wifi-broadcast.cc'
    set_properties(obj)

    obj = bld.create_ns3_program('kodo-wired-broadcast',
                                 ['core', 'applications', 'point-to-point',
                                  'point-to-point-layout', 'internet'])
    obj.source = 'kodo-wired-broadcast.cc'
    set_properties(obj)


