#! /usr/bin/env python
# encoding: utf-8

ns3_build = bld.env['NS3_BUILD']
ns3_libs = bld.env['NS3_LIBS']

bld.program(
    features='cxx test',
    source=['main.cc'],
    target='encoder_recoder_decoder',
    libpath=ns3_build,
    rpath=ns3_build + ['.'],
    includes=ns3_build,
    lib=ns3_libs,
    use=['kodocpp_includes'])
