#! /usr/bin/env python
# encoding: utf-8

ns3_build = bld.env['NS3_BUILD']
ns3_libs = bld.env['NS3_LIBS']

bld.program(
    features='cxx cxxprogram',
    source=['main.cpp'],
    target='wired_broadcast',
    libpath=ns3_build,
    rpath=ns3_build,
    includes=ns3_build,
    lib=ns3_libs,
    use=['kodo_includes', 'fifi_includes', 'sak_includes',
         'boost_includes', 'platform_includes', 'cpuid_includes'])
